# Changes here will be overwritten by Copier
_commit: v1
_src_path: git+https://github.com/WaylonWalker/markata-blog-starter
author_email: pypeaday@pype.dev
author_fullname: Pypeaday
author_twitter: '@pypeaday'
description: A blog created from the markata blog-starter
project_name: pype.dev
python_package_import_name: pype_dev
url: https://pype.dev

