#
#  __  __            _         _         _                  _
# |  \/  | __ _ _ __| | ____ _| |_ __ _ | |_ ___  _ __ ___ | |
# | |\/| |/ _` | '__| |/ / _` | __/ _` || __/ _ \| '_ ` _ \| |
# | |  | | (_| | |  |   < (_| | || (_| || || (_) | | | | | | |
# |_|  |_|\__,_|_|  |_|\_\__,_|\__\__,_(_)__\___/|_| |_| |_|_|
#
#                                           nicpayne.com

[markata]
# bump site version to bust GitHub actions cache
# site_version = 15

# 2 weeks in seconds
default_cache_expire = 1209600

## Markata Setup
glob_patterns = "pages/**/*.md"
output_dir = "markout"
assets_dir = "static"
hooks = [
   "markata.plugins.publish_source",
   "markata.plugins.publish_dev_to_source",
   "plugins.render_template_variables",
   "plugins.codeblocks",
   "plugins.index",
   "plugins.slug",
   "plugins.one_line_link",
   "plugins.include",
   "default",
   # 'plugins.related',
   'plugins.seo_amp',
   'plugins.publish_amp',
   'plugins.custom_seo',
   'plugins.gif_to_mp4',
   'plugins.youtube',
   'plugins.rss_tag',
   'plugins.auto_publish',
   ]
disabled_hooks = ["markata.plugins.covers", 'markata.plugins.flat_slug']

## Site Config
url = "https://blog.paynepride.com"
images_url = "/static/images"  # nothing yet
title = "Nic's mental data lake"
description = "I write about how I use python for data-centric work and my homelab journey"
rss_description = "Pypeaday posts"
author_name = "Nicholas Payne"
author_email = "nicpayne713@gmail.com"
icon = "bitmoji.png"
lang = "en"
post_template = "pages/templates/post_template.html"
amp_template = "pages/templates/post_template.amp.html"
theme_color = "#3A8695"
background_color = "#3A9577"
start_url = "/"
site_name = "Pypeaday"
short_name = "pype"
display = "minimal-ui"
twitter_card = "summary_large_image"
twitter_creator = "@pypeaday"
twitter_site = "@pypeaday"

[markata.auto_publish.filters]
til='templateKey=="til" and date<=today'

[markata.archive]
archive_template="pages/templates/archive_template.html"

[markata.archive.pages.archive]
filter="date<=today and templateKey in ['blog-post', 'til'] and status.lower()=='published'"

[markata.archive.pages.blog]
filter="date<=today and templateKey in ['blog-post'] and status.lower()=='published'"

[markata.archive.pages.draft]
filter="status=='draft'"

[markata.archive.pages.scheduled]
filter="date>today"

[markata.archive.pages.today]
filter="date==today"

[markata.archive.pages.python]
filter="date<=today and 'python' in tags"

[markata.archive.pages.python-draft]
filter="date<=today and 'python' in tags and status=='draft'"

[markata.archive.pages.linux]
filter="date<=today and 'linux' in tags"

[markata.archive.pages.linux-draft]
filter="date<=today and 'linux' in tags and status=='draft'"

[markata.archive.pages.vim]
filter="date<=today and 'vim' in tags"

[markata.archive.pages.vim-draft]
filter="date<=today and 'vim' in tags and status=='draft'"

[markata.archive.pages.kedro]
filter="date<=today and 'kedro' in tags"

[markata.archive.pages.kedro-draft]
filter="date<=today and 'kedro' in tags and status=='draft'"

[markata.archive.pages.homelab]
filter="date<=today and 'homelab' in tags"

[markata.archive.pages.kedro-draft]
filter="date<=today and 'kedro' in tags and status=='draft'"

[markata.archive.pages.til]
template="pages/templates/archive_template.html"
# card_template="pages/templates/gratitude_card.html"
filter="date<=today and templateKey == 'til'"

[markata.archive.pages.til-vim]
template="pages/templates/archive_template.html"
# card_template="pages/templates/gratitude_card.html"
filter="date<=today and templateKey == 'til' and 'vim' in tags"

[[markata.covers]]
name='-dev'
template = "static/cover-template.png"
font = "./.github/scripts/waterlilly-script.ttf"
font_color = "rgb(255,255,255)"

[[markata.covers]]
name='-og'
template = "static/og-template.png"
font = "./.github/scripts/waterlilly-script.ttf"
font_color = "rgb(255,255,255)"
# text_key = 'long_description'
text_font = "./static/JosefinSans-Regular.ttf"
text_font_color = "rgb(200,200,200)"

[[markata.covers]]
name='-hashnode'
template = "static/hashnode-template.png"
font = "./.github/scripts/waterlilly-script.ttf"
font_color = "rgb(255,255,255)"

[[markata.seo]]
name = "og:type"
property = "og:type"
content = "article"

[[markata.seo]]
name = "og:author"
property = "og:author"
content = "Nicholas Payne"

[[markata.seo]]
name = "og:site_name"
property = "og:site_name"
content = "Nicholas Payne"

[[markata.seo]]
name = "theme-color"
content="#3A5895"
